### ISSUE TITLE
Problem in Russian Language

### ISSUE THREAD

**Issue by EternityOne** [nishantapps/BardForum#1]
With Russian characters, it gives the error below

Error: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["text"]
    at ClientRequest.setHeader (node:_http_outgoing:651:3)
    at new ClientRequest (node:_http_client:291:14)
    at Object.request (node:https:358:10)
    at RedirectableRequest._performRequest (/root/discord/Support/node_modules/follow-redirects/index.js:284:24)
    at new RedirectableRequest (/root/discord/Support/node_modules/follow-redirects/index.js:66:8)
    at Object.request (/root/discord/Support/node_modules/follow-redirects/index.js:523:14)
    at dispatchHttpRequest (/root/discord/Support/node_modules/axios/dist/node/axios.cjs:2861:21)
    at /root/discord/Support/node_modules/axios/dist/node/axios.cjs:2568:5
    at new Promise (<anonymous>)
    at wrapAsync (/root/discord/Support/node_modules/axios/dist/node/axios.cjs:2548:10) {
  code: 'ERR_INVALID_CHAR'
}

**Comment by npmnishantsharma** [comment]
This is axios error
